default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123

development:
  <<: *default
  database: postgres
  username: postgres
  password: 123

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: postgres